name: Windows .NET framework CI/CD Pipeline
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Framework
        uses: microsoft/setup-msbuild@v3

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.USERPROFILE }}\.nuget\packages
            packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config', '**/MathDemoCode.csproj', 'NuGet.config') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build solution
        run: msbuild MSTestDemo.sln /p:Configuration=Debug -restore

      - name: Run tests
        run: |
          $Env:Path += ";C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow"
          vstest.console.exe MathDemoCode\bin\Debug\net48\MathDemoCode.dll "/logger:trx;LogFileName=UnitTest.trx" "/ResultsDirectory:TestResults"

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/bin/Debug/*
            **/bin/Release/*
            TestResults/*
